# .github/workflows/publish.yml
name: 🧪 Publish Tauri App

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install Ubuntu dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1 libappindicator3-dev librsvg2-dev patchelf

      - name: Install Windows dependencies
        if: matrix.platform == 'windows-latest'
        run: choco install webview2 -y

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install frontend dependencies
        run: pnpm install      

      - name: Rename macOS build output
        if: matrix.platform == 'macos-latest'
        run: |
          # Détecte l'architecture à partir des arguments
          if [[ "${{ matrix.args }}" == *"aarch64"* ]]; then
            ARCH="arm64"
          else
            ARCH="x64"
          fi
          # Adapte ce chemin selon ta sortie Tauri
          DMG_PATH=$(find src-tauri/target -name "*.dmg" | head -n 1 || true)
          APP_PATH=$(find src-tauri/target -name "*.app" | head -n 1 || true)
          if [ -n "$DMG_PATH" ]; then
            mv "$DMG_PATH" "Tout-Do-mac-${ARCH}.dmg"
          fi
          if [ -n "$APP_PATH" ]; then
            zip -r "Tout-Do-mac-${ARCH}.zip" "$APP_PATH"
          fi

      - name: Build & Upload via Tauri Action
        uses: tauri-apps/tauri-action@v0.5.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'Tauri app built for each platform'
          releaseDraft: false
          prerelease: true
          args: ${{ matrix.args }} --verbose